=== howlsmovingrepository/xml-mp3-pt.2/ammangus_project2-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="mp3">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="artist" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="membersIFgroup" type="gopType"/>
                            <!-- i know the rubric asked for minOccurs="0" maxOccurs="unbounded" on members, but with how i've set up the document
                                it makes more sense to have this element with its attribute occuring once & no min of zero -->
                            <xs:element name="startcareer" type="startType" minOccurs="0"/>
                            <xs:element name="genre" type="xs:string" minOccurs="0"
                                maxOccurs="unbounded"/>
                            <xs:element name="endcareer" type="xs:gYear" minOccurs="0"/>
                            <!-- endcareer elements in doc have been deleted for all artists with null values -->
                            <xs:element name="country"/>
                            <xs:element name="album" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="image" type="imageType"> </xs:element>
                                        <xs:element name="citation" type="xs:string"/>
                                        <xs:element name="comment" minOccurs="0" type="commentType"/>
                                        <xs:element name="rating" type="ratingType"/>
                                        <xs:element name="producer" type="xs:string" minOccurs="0"/>
                                        <xs:element name="engineersmixers" type="xs:string"
                                            minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="songwriters" type="xs:string"
                                            minOccurs="0"/>
                                        <xs:element name="masteringengineer" type="xs:string"
                                            minOccurs="0"/>
                                        <xs:element name="a_label" type="xs:string"/>
                                        <xs:element name="tracks" type="trackType"/>
                                        <xs:element name="releases" type="releaseType"/>
                                    </xs:sequence>
                                    <xs:attribute name="albumname" type="xs:string" use="required"/>
                                    <xs:attribute name="albumtype" type="productType" use="required"/>
                                    <xs:attribute name="a_sku" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="K315F2020[A-Z]{1}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="catagory" type="catagoryType" use="required"/>

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="artistname" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="gopType" mixed="true">
        <xs:attribute name="groupORperson">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="person"/>
                    <xs:enumeration value="group"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="startType">
        <xs:restriction base="xs:string">
            <!-- would have made this a gYear, but i'm trying to follow directions -->
            <xs:pattern value="\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="imageType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".+[.]jpeg"/>
            <xs:pattern value=".+[.]jpg"/>
            <xs:pattern value=".+[.]gif"/>
            <xs:pattern value=".+[.]png"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="commentType">
        <xs:restriction base="xs:string">
            <xs:minLength value="10"/>
            <xs:maxLength value="200"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ratingType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="trackType">
        <xs:sequence>
            <xs:element name="track" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="rankposition" type="xs:positiveInteger"/>
                        <xs:element name="length">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value=".*.*:\d{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="writers" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                    <xs:attribute name="albumref" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:IDREF">
                                <xs:pattern value="K315F2020[A-Z]{1}"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="type" type="productType"> </xs:attribute>
                    <xs:attribute name="t_sku">
                        <xs:simpleType>
                            <xs:restriction base="xs:ID">
                                <xs:pattern value="K315F2020[A-Z]{1}\d{3}"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="releaseType">
        <xs:sequence>
            <xs:element name="release" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="date" type="dateType" minOccurs="0"/>
                        <xs:element name="r_label" type="xs:string" minOccurs="0"/>
                        <xs:element name="r_catalogue_number" type="xs:string" minOccurs="0"/>
                        <xs:element name="r_barcode" type="xs:string" minOccurs="0"/>
                        <xs:element name="format" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="CD"/>
                                    <xs:enumeration value="Digital Media"/>
                                    <xs:enumeration value="Vinyl"/>
                                    <xs:enumeration value="12&quot; Vinyl"/>
                                    <xs:enumeration value="7x7&quot; Vinyl"/>
                                    <xs:enumeration value="2x12&quot; Vinyl"/>
                                    <xs:enumeration value="Cassette"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="r_country" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
            <xs:pattern value="\d{4}-\d{2}"/>
            <xs:pattern value="[A-Z]{2}\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="catagoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Grammy_Winner"/>
            <xs:enumeration value="Grammy_Nominee"/>
            <xs:enumeration value="Personal_Favorite"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="productType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="album"/>
            <xs:enumeration value="song"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== howlsmovingrepository/xml-mp3-pt.2/ammangus_project2-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<mp3 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ammangus_project2-2.xsd">
    <artist artistname="Billie Eilish">
        <membersIFgroup groupORperson="person"/>
        <startcareer>2016</startcareer>
        <genre>pop</genre>
        <country>USA</country>
        <album albumname="When We All Fall Asleep, Where Do We Go?" albumtype="album"
            a_sku="K315F2020A" catagory="Grammy_Winner">
            <image>billie.jpg</image>
            <citation>theguardian.com</citation>
            <comment>wish u were gay is not about a girl, automatic -1</comment>
            <rating>7</rating>
            <producer>Finneas O'Connell</producer>
            <engineersmixers>Rob Kinelski &amp; Finneas O'Connell</engineersmixers>
            <songwriters>Billie Eilish O'Connell &amp; Finneas O'Connell</songwriters>
            <masteringengineer>John Greenham</masteringengineer>
            <a_label>interscope</a_label>
            <tracks>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A001">
                    <title>!!!!!!!</title>
                    <rankposition>1</rankposition>
                    <length>0:13</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A002">
                    <title>bad guy</title>
                    <rankposition>2</rankposition>
                    <length>3:14</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A003">
                    <title>xanny</title>
                    <rankposition>3</rankposition>
                    <length>4:03</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A004">
                    <title>you should see me in a crown</title>
                    <rankposition>4</rankposition>
                    <length>3:00</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A005">
                    <title>all the good girls go to hell</title>
                    <rankposition>5</rankposition>
                    <length>2:48</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A006">
                    <title>wish you were gay</title>
                    <rankposition>6</rankposition>
                    <length>3:41</length>
                    <writers>Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A007">
                    <title>when the party's over</title>
                    <rankposition>7</rankposition>
                    <length>3:16</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A008">
                    <title>8</title>
                    <rankposition>8</rankposition>
                    <length>2:53</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A009">
                    <title>my strange addiction</title>
                    <rankposition>9</rankposition>
                    <length>2:59</length>
                    <writers>Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A010">
                    <title>bury a friend</title>
                    <rankposition>10</rankposition>
                    <length>3:13</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A011">
                    <title>ilomilo</title>
                    <rankposition>11</rankposition>
                    <length>2:36</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A012">
                    <title>listen before i go</title>
                    <rankposition>12</rankposition>
                    <length>4:02</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A013">
                    <title>i love you</title>
                    <rankposition>13</rankposition>
                    <length>4:51</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
                <track albumref="K315F2020A" type="song" t_sku="K315F2020A014">
                    <title>goodbye</title>
                    <rankposition>14</rankposition>
                    <length>1:59</length>
                    <writers>Billie Eilish / Finneas O'Connell</writers>
                </track>
            </tracks>
            <releases>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>B0029727-02</r_catalogue_number>
                    <r_barcode>602577427626</r_barcode>
                    <format>CD</format>
                    <r_country>AU</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Interscope Records, Darkroom</r_label>
                    <r_catalogue_number>B0029729-01, B0029729-01JK02</r_catalogue_number>
                    <r_barcode>602577427664</r_barcode>
                    <format>12" Vinyl</format>
                    <r_country>CA, US</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>602577427626</r_catalogue_number>
                    <r_barcode>602577427626</r_barcode>
                    <format>CD</format>
                    <r_country>XE</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>602577588037</r_catalogue_number>
                    <r_barcode>602577427664</r_barcode>
                    <format>12" Vinyl</format>
                    <r_country>IE, GB</r_country>
                </release>

                <release>
                    <date>2019-03-29</date>
                    <r_label>Interscope Records</r_label>
                    <r_catalogue_number>UICS-1350</r_catalogue_number>
                    <r_barcode>4988031321645</r_barcode>
                    <format>CD</format>
                    <r_country>JP</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>B0029727-02</r_catalogue_number>
                    <r_barcode>602577427626</r_barcode>
                    <format>CD</format>
                    <r_country>GB</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>[none]</r_catalogue_number>
                    <r_barcode>602508481703</r_barcode>
                    <format>Digital Media</format>
                    <r_country>US</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>B0029727-02</r_catalogue_number>
                    <r_barcode>602577427626</r_barcode>
                    <format>CD</format>
                    <r_country>US</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number/>
                    <r_barcode>602577427640</r_barcode>
                    <format>Digital Media</format>
                    <r_country>XW</r_country>
                </release>
                <release>
                    <date>2019-03-29</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number/>
                    <r_barcode>602577427657</r_barcode>
                    <format>Digital Media</format>
                    <r_country>XW</r_country>
                </release>
                <release>
                    <date>2019-12-09</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>B0031217-1</r_catalogue_number>
                    <r_barcode>602508310270</r_barcode>
                    <format>7x7" Vinyl</format>
                    <r_country>US, XE</r_country>
                </release>


                <release>
                    <date>2019-12-13</date>
                    <r_label>Darkroom, Interscope Records</r_label>
                    <r_catalogue_number>602508556517</r_catalogue_number>
